# routes:
#   /:
#     data: page.home
#     template: page

# collections:
#   /blog/:
#     permalink: /blog/{slug}/
#     template: index
#     filter: 'tag:-hash-customhome'

# taxonomies:
#   tag: /blog/topic/{slug}/
#   author: /blog/author/{slug}/
routes:

collections:
  /:
    permalink: /{slug}/
    template: index

  /aicontext/:
    permalink: /aicontext/{slug}/
    template: aicontext
    filter: tag:aiconrext

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
